### ISSUE TITLE
Customising url path

### ISSUE THREAD

**Issue by williamkennedy** [excid3/prefixed_ids#12]
Hey Chris,

Love this library. I was just wondering if the following is possible. If not, that's OK, would it be OK for me to add it? 

I would like custom URLs but with prefix at the start. 

Let's say we have the following:

```
class Article < ApplicationRecord
  has_prefix_id :article
end
```

This will generate the following id:

```
article.prefix_id = article_d6AgwY7bGQLkPiZprxnm5Mva
```

I was wondering if it's possible to do the following:

```
# title: String
class Article < ApplicationRecord
  has_prefix_id :article, custom_path: title
end
```

```
article.title ='Hello world'
article.save
article.prefix_id => article_d6AgwY7bGQLkPiZprxnm5Mva_hello-world
```

Is this possible at the moment or would be OK to add it?

**Comment by excid3** [comment]
Interesting, what's the use case here? SEO?
