### ISSUE TITLE
Refactor to work like hashid-rails

### ISSUE THREAD

**Issue by excid3** [excid3/prefixed_ids#3]
Currently, we require a column in the database to store the prefix ID. Using a HashID + Prefix would allow us to skip that entirely and mask the database ID. This would be much easier to use and more user friendly.

https://github.com/jcypret/hashid-rails

**Comment by swanson** [comment]
Looks like there a PR (that didn't get merged) to basically add this functionality to HashID (if you didn't want a separate gem): https://github.com/jcypret/hashid-rails/pull/62

**Comment by excid3** [comment]
Nice, wonder why it was closed.

**Comment by excid3** [comment]
Released as 1.1
