### ISSUE TITLE
Salt Initializer 

### ISSUE THREAD

**Issue by Kentasmic** [excid3/prefixed_ids#32]
I think the text in the initializer and documentation should be :

PrefixedIds.salt = "usersalt"

instead of what is in the documentation: 

PrefixID.salt = "usersalt"

**Comment by excid3** [comment]
Want to send a PR to fix it?

**Comment by Kentasmic** [comment]
Sure! But first I will need to figure out how to do that. 🤔😀

I will try to do that tonight. 

Kent

On October 26, 2022, "dependabot[bot]" ***@***.***> wrote:
> Want to send a PR to fix it?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/excid3/prefixed_ids/issues/32#issuecomment-
1291486974>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AQPMWL56HG5EWGJ6KCMVYG3WFCYBJANCNFSM6AAAAAAROQTZGU>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by Kentasmic** [comment]
Done! (edited readme)

**Comment by excid3** [comment]
Fixed by #33 (I created the PR for you)

**Comment by Kentasmic** [comment]
Thanks! A GoRails video on how to do super simple pull requests would be
a great video! I saw the request.js one but that is more involved, I
mean more for typos in the readme or very simple Ruby changes and not js
stuff with yarn/webpacker etc.

On October 26, 2022, "dependabot[bot]" ***@***.***> wrote:
> Fixed by #33 <https://github.com/excid3/prefixed_ids/pull/33> (I
> created the PR for you)
>

—
Reply to this email directly, view it on GitHub
<https://github.com/excid3/prefixed_ids/issues/32#issuecomment-
1292780350>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AQPMWL5JL3ZEZKYJEVVZSLDWFG623ANCNFSM6AAAAAAROQTZGU>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by excid3** [comment]
That's a great idea. I'll add it to our backlog! 👍
