### ISSUE TITLE
UUIDs

### ISSUE THREAD

**Issue by rikkipitt** [excid3/prefixed_ids#4]
Hey @excid3,

Thanks for creating this library, it's come at a super handy time. I'm building a webhook system for a project I'm working on and this is ideal. However, I've come across an issue where the underlying `hashids` gem only works with integers (and hex) by the looks of things. However, I have a couple of models where the primary key is a UUID...

I can use the UUID in the webhook serializer, but it would be awesome to be able to have matching prefixed behaviour. Even if it's just to keep things uniform.

Think this is something you'd accept as a PR at all?

**Comment by excid3** [comment]
I think so. The main thing you'd need to change is these 3 methods:

https://github.com/excid3/prefixed_ids/blob/master/lib/prefixed_ids/prefix_id.rb#L9-L22

Maybe we can make that interchangeable so you can provide any object that responds to `new`, `encode(id)` and `decode_id(id, **options)`

**Comment by heka1024** [comment]
Hi. I'm interested in this issue. Could you assign this to me?

**Comment by excid3** [comment]
Looking back at this today. Since UUIDs are already unique, I don't know that it'll make sense to support in the gem.

For example, it would be as simple as adding a method to strip the prefix from the UUID.
```ruby
# acct_123e4567-e89b-12d3-a456-426614174000
def self.find_by_prefix_uuid(prefixed_uuid)
  find(prefixed_uuid.split("_").last)
end
```
