### ISSUE TITLE
ActiveRecord's .find still works with normal IDs

### ISSUE THREAD

**Issue by fuchsfelipel** [excid3/prefixed_ids#43]
Hi,

I noticed that prefixed_ids doesn't prevent `.find(params[:id)` from working with original IDs. Eg., both examples below work:

- `localhost:3000/users/user_oEw7akrBJ3Em5tk32ZxRP9Yp`
- `localhost:3000/users/1`

I believe that this behavior should be changed, or clearly documented on the README since users who expect IDs to be really unguessable could be targeting potential security issues.

@excid3 tell me if your prefer documenting or changing the behavior, I'll happily e commit it.

**Comment by excid3** [comment]
You should use `User.find_by_prefix_id` explicitly if you only want to find by the prefixed ID.

**Comment by fuchsfelipel** [comment]
Ok! I'll document it...
