### ISSUE TITLE
PrefixedIds.models and thus .find is missing most models which have a prefixed ID defined

### ISSUE THREAD

**Issue by kylebragger** [excid3/prefixed_ids#72]
We are using prefixed_ids in our app (Rails 7.1.3.2, Ruby 3.1.5p252) and it appears that it is not fully detecting all models which are using `has_prefix_id`. The screenshot below shows all of the models which should have one:

<img width="164" alt="Screenshot 2024-08-16 at 7 44 19 AM" src="https://github.com/user-attachments/assets/b9733593-3f59-42fb-b394-f2199fc66645">

Calling `.models` only returns two:

```
PrefixedIds.models
{
    "rule" => class Rule < ApplicationRecord {
                 :id => :integer,
                <SNIP>
    },
    "user" => class User < ApplicationRecord {
                     :id => :integer,
                     <SNIP>
    }
}
```

Thus trying to call `.find` only works with Rule and User.

```
PrefixedIds.find('secl_ewB2M9Yl8ryQIBJLVdAn6aky')
/Users/kyle/.rbenv/versions/3.1.5/gemsets/ticketco-web/gems/prefixed_ids-1.6.1/lib/prefixed_ids.rb:22:in `rescue in find': Unable to find model with prefix `secl`. Available prefixes are: rule, user (PrefixedIds::Error)
```

There's an initializer which sets the salt (below) but otherwise no special config or weird stuff going on.

`PrefixedIds.salt = ENV.fetch('PREFIX_ID_SALT')`

I couldn't really deduce anything of note reading thru `https://github.com/excid3/prefixed_ids/blob/main/lib/prefixed_ids.rb` -- it appears it should be registering the model when `has_prefix_id` is used.

**Comment by kylebragger** [comment]
Update: it may be related to rails console. For whatever reason, some of our models are showing up already registered when a new console session is started, whereas others need some kind of other interaction to be loaded and thus have has_prefix_id called. It's a very vanilla app in terms of setup, so maybe "user error" in this case.

**Comment by excid3** [comment]
Yeah, Rails autoloads in development so nothing is available until it's loaded for the first time.

**Comment by kylebragger** [comment]
@excid3 yeah, totally my bad here. thanks for the quick reply!

**Comment by excid3** [comment]
No worries! I had considered removing this because of that confusion, but it's also kinda useful.

You can eager load in development to make this work, for anyone that runs across this issue.
