### ISSUE TITLE
PrefixedIds::Error raised when trying to PrefixedIds.find an instance of a class never loaded before 

### ISSUE THREAD

**Issue by jumichot** [excid3/prefixed_ids#9]
Hi there ! Thank you for this project. I'm trying to use it for obfuscating the database id of a model on public pages, but 
I think there is a loading problem with the gem.

The available models that can be found with PrefixedIds.find are not in the list until there are called somewhere.
`has_prefix_id :plan` doesn't seem to have any effet before calling somewhere the model

The problem I face :  if the first line of a controller is trying to find an instance (for example Plan on jumpstart pro) with `PrefixedIds.find("plan_...")`, it raises a PrefixedIds::Error, telling me Plan is not available for this gem (and this model has   has_prefix_id :plan)

Steps to reproduce :
- clone jumpstart pro 
- go into StaticController
- in rails console fetch the id of the first plan 
  ```
  [2] pry(main)> Plan.first.prefix_id
    Plan Load (1.2ms)  SELECT "plans".* FROM "plans" ORDER BY "plans"."id" ASC LIMIT $1  [["LIMIT", 1]]
  => "plan_9jolLRz1nJAKZSA8EWZypP"
  ```
- try to find the instance 
  ```
  class StaticController < ApplicationController
    def index
      PrefixedIds.find("plan_9jolLRz1nJAKZSA8EWZypP")
    end
    ```
- stop the server and reload : the error should happen

Now load any other instance of Plan
```
class StaticController < ApplicationController
  def index
    Plan.first
    PrefixedIds.find("plan_9jolLRz1nJAKZSA8EWZypP")
  end
  ```
 - stop the server and reload, this should work

**Comment by excid3** [comment]
Make sure your app has loaded all the models. Otherwise, if you know it's a Plan, just query on the model directly. `Plan.find("plan_9jolLRz1nJAKZSA8EWZypP")`

**Comment by jumichot** [comment]
> Make sure your app has loaded all the models.
Not sure how I should do that

> Otherwise, if you know it's a Plan, just query on the model directly.
Yes I ended up using `.find_by_prefix_id` and the problem is gone. So we can probably close this issue

**Comment by excid3** [comment]
Development lazy loads by default which is why it doesn't find all the models. You would have to eager load your models to use that.

It's best to explicitly use the model anyways. 👍
